/**
 * Turns pasted rich text into SQL you can run against any database.
 *
 *   # save the clipboard's HTML flavour, not its plain text
 *   xclip -selection clipboard -t text/html -o > clues.html     # X11
 *   wl-paste --type text/html > clues.html                      # Wayland
 *
 *   npx vite-node scripts/clues-from-html.ts clues.html > clues.sql
 *
 * Each heading in the file names a location; everything until the next heading
 * is that location's clue, converted to the clue markup (**bold**, *italic*,
 * blank line for a verse, --- for the ornament rule).
 *
 * Output is INSERTs only — no deletes, no updates — so running it twice adds
 * rows rather than destroying any. Read it before you run it; that is the point
 * of emitting SQL rather than writing to the database from here.
 */
import { readFileSync } from 'node:fs'
import { splitClueSections } from '../src/lib/htmlToClue'

const [file] = process.argv.slice(2)
if (!file) {
  console.error('usage: vite-node scripts/clues-from-html.ts <pasted.html>')
  process.exit(1)
}

const sections = splitClueSections(readFileSync(file, 'utf8'))
if (sections.length === 0) {
  console.error('No clues found. Is the file the HTML flavour of the clipboard, with a heading per location?')
  process.exit(1)
}

/** Dollar quoting, so clue text with quotes, newlines or backslashes needs no escaping. */
function quote(text: string): string {
  let tag = 'clue'
  while (text.includes(`$${tag}$`)) tag += '_'
  return `$${tag}$${text}$${tag}$`
}

const lines = [
  '-- Generated by scripts/clues-from-html.ts. Review before running.',
  `-- ${sections.length} location${sections.length === 1 ? '' : 's'}.`,
  'begin;',
  '',
]

sections.forEach((section, index) => {
  const name = section.name || `Location ${index + 1}`
  lines.push(
    'insert into public.stations (name, clue_text, sort_order)',
    `select ${quote(name)}, ${quote(section.clue)},`,
    '       coalesce((select max(sort_order) from public.stations), 0) + 1',
    // `stations` has no unique name, so guard by name rather than ON CONFLICT:
    // re-running the file then adds nothing instead of duplicating the place.
    `where not exists (select 1 from public.stations where name = ${quote(name)});`,
    '',
  )
})

lines.push(
  '-- Codes, routes and the treasure are set in the admin UI: they are minted',
  '-- server-side and have to satisfy the staggering rules.',
  'commit;',
)

console.log(lines.join('\n'))
