/**
 * Turns a chat paste of per-team clues into one SQL file you run by hand.
 *
 *   npx vite-node scripts/seed-teams-from-chat.ts sample.html Pookalam Maveli Chenda Sadya > seed-prod.sql
 *
 * The paste is expected to label each clue `Team 1 - Q1:`; team numbers map to
 * the names you pass, in order, and question N becomes that team's level N.
 *
 * Why a location per team-question: `stations.clue_text` is one clue per place,
 * shared by everyone, but these clues are written per team — four different
 * riddles for level 1. So each team's stop becomes its own row, named
 * "<Team> · Clue N". The physical place may be shared between teams; the app
 * simply does not need to know that, and the staggering constraints are then
 * satisfied by construction.
 *
 * Emits INSERTs only, each guarded so a second run adds nothing. Codes are
 * generated here (this is a paper game; they are printed and posted), from the
 * same alphabet the server uses — no I, O, 0 or 1, so a handwritten slip cannot
 * be misread.
 *
 * The treasure is NOT set: it is one shared place with one shared code for the
 * whole field, and this paste has no shared final clue. Pick it on the Stations
 * page before starting, or the kickoff refuses with `no_treasure`.
 */
import { readFileSync } from 'node:fs'
import { randomInt } from 'node:crypto'
import { splitTeamQuestions } from '../src/lib/htmlToClue'

const [file, ...teamNames] = process.argv.slice(2)
if (!file || teamNames.length === 0) {
  console.error('usage: vite-node scripts/seed-teams-from-chat.ts <paste.html> <team1> <team2> …')
  process.exit(1)
}

const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
const used = new Set<string>()
function code(): string {
  for (;;) {
    let value = ''
    for (let i = 0; i < 6; i++) value += ALPHABET[randomInt(ALPHABET.length)]
    if (!used.has(value)) {
      used.add(value)
      return value
    }
  }
}

function quote(text: string): string {
  let tag = 'q'
  while (text.includes(`$${tag}$`)) tag += '_'
  return `$${tag}$${text}$${tag}$`
}

const clues = splitTeamQuestions(readFileSync(file, 'utf8'))
if (clues.length === 0) {
  console.error('No `Team N - QM` markers found in that file.')
  process.exit(1)
}

const teams = [...new Set(clues.map(c => c.team))].sort((a, b) => a - b)
if (teams.length > teamNames.length) {
  console.error(`The paste has ${teams.length} teams but only ${teamNames.length} names were given.`)
  process.exit(1)
}

const nameOf = new Map(teams.map((number, index) => [number, teamNames[index]]))
const teamCodes = new Map(teams.map(number => [number, code()]))
const out: string[] = [
  '-- Generated by scripts/seed-teams-from-chat.ts. Review before running.',
  `-- ${teams.length} teams, ${clues.length} clues.`,
  '--',
  '-- Run in the SQL editor of the target project. Every statement is guarded, so',
  '-- running it twice changes nothing. It sets no treasure: pick that on the',
  '-- Stations page (one shared place, one shared code) before Start hunt.',
  'begin;',
  '',
]

for (const number of teams) {
  out.push(
    'insert into public.teams (name, team_code)',
    `select ${quote(nameOf.get(number)!)}, ${quote(teamCodes.get(number)!)}`,
    `where not exists (select 1 from public.teams where name = ${quote(nameOf.get(number)!)});`,
    '',
  )
}

const cellCodes = new Map<string, string>()
for (const clue of clues) {
  const station = `${nameOf.get(clue.team)} · Clue ${clue.question}`
  cellCodes.set(`${clue.team}:${clue.question}`, code())
  out.push(
    'insert into public.stations (name, clue_text, sort_order)',
    `select ${quote(station)}, ${quote(clue.clue)},`,
    '       coalesce((select max(sort_order) from public.stations), 0) + 1',
    `where not exists (select 1 from public.stations where name = ${quote(station)});`,
    '',
  )
}

for (const clue of clues) {
  const station = `${nameOf.get(clue.team)} · Clue ${clue.question}`
  out.push(
    'insert into public.team_stations (team_id, level, station_id, code)',
    'select t.id, ' + clue.question + ', s.id, ' + quote(cellCodes.get(`${clue.team}:${clue.question}`)!),
    'from public.teams t, public.stations s',
    `where t.name = ${quote(nameOf.get(clue.team)!)} and s.name = ${quote(station)}`,
    '  and not exists (',
    '    select 1 from public.team_stations x where x.team_id = t.id and x.level = ' + clue.question,
    '  );',
    '',
  )
}

out.push('commit;', '')
out.push('-- Codes to print. Team code is the login; the rest are posted at each place.')
for (const number of teams) {
  out.push(`--   ${nameOf.get(number)}  login ${teamCodes.get(number)}`)
  for (const clue of clues.filter(c => c.team === number)) {
    out.push(`--     level ${clue.question}: ${cellCodes.get(`${number}:${clue.question}`)}`)
  }
}

console.log(out.join('\n'))
